import { getPerson, listFactsForPerson, getBrief, upsertBrief, markBriefStale } from "@/lib/repo";
import { getAdapter } from "@/lib/ai";
import type { BriefContent } from "@/lib/ai/types";
import { contactCadenceDays, SELF_ID } from "@/lib/nightshift/scout";
import { localToday } from "@/lib/today";

// Pre-Read generation: turn a person's facts into the cached three-block brief.
// This is the one place a brief is built, shared by the manual refresh route, the
// first-open (never-empty) path, and the background refresh worker. Pure with
// respect to the AI: the qualitative read / insights / recommendations come from
// the adapter, but the DETERMINISTIC lines (the contact rhythm and the count of
// notes filed since the last prep) are computed here and prepended, so a number
// is never left to the model to invent.

// The freshness window: a brief older than this is regenerated by the background
// pass even if nothing changed, so a long-quiet profile is never stale forever.
export const BRIEF_STALE_DAYS = 2;

// Regenerate and cache one person's brief, returning the fresh content. Returns
// null for an unknown person or the diary self row (which is never briefed).
// Throws if the underlying AI call fails, so the caller decides whether to retry
// (the worker skips, a manual refresh surfaces the error).
export async function generateBriefFor(personId: string): Promise<BriefContent | null> {
  if (personId === SELF_ID) return null;
  const person = getPerson(personId);
  if (!person) return null;

  const rows = listFactsForPerson(personId); // newest first, carries created_at
  const facts = rows.map((r) => r.content);
  const cached = getBrief(personId);
  const cadenceDays = contactCadenceDays(rows.map((r) => r.created_at));
  const today = localToday();

  // Coarse "what changed" diff: facts filed since the brief we are replacing.
  const newFacts = cached ? rows.filter((r) => r.created_at > cached.generated_at).map((r) => r.content) : [];

  const adapter = getAdapter();
  const out = await adapter.brief({
    person: { id: person.id, name: person.name, company: person.company, role: person.role, blurb: person.blurb },
    facts,
    newFacts,
    cadenceDays,
    today,
  });

  // Prepend the deterministic, never-hallucinated insight lines. Only the STABLE
  // cadence goes in (no absolute "N days ago" — that would be frozen into the
  // cache and read wrong as the days pass); recency is served by Warm-Keeper and
  // the new-since line below.
  const lead: string[] = [];
  if (cadenceDays !== null) lead.push(`You usually talk about every ${cadenceDays} days.`);
  if (newFacts.length) {
    lead.push(`${newFacts.length} new ${newFacts.length === 1 ? "note" : "notes"} since your last prep.`);
  }

  const content: BriefContent = {
    read: out.read,
    insights: [...lead, ...out.insights].slice(0, 6),
    recommendations: out.recommendations.slice(0, 5),
  };

  // `await adapter.brief` above is the only yield point; better-sqlite3 is
  // synchronous, so everything from here to the end runs without interleaving.
  // If the person's facts changed DURING that await (a note captured, a promise
  // ticked done, a note edited or removed all ran markBriefStale), the brief we
  // are about to store is already behind. upsertBrief clears stale=0, so re-flag
  // it: the "facts changed" banner shows and the next pass regenerates with the
  // change, instead of silently presenting an out-of-date read as current. The
  // signature covers id, status, and content, so add / delete / toggle / edit are
  // all caught, not just a new note.
  const changedDuringGen = factSignature(listFactsForPerson(personId)) !== factSignature(rows);

  upsertBrief({ personId, body: JSON.stringify(content), sourceFactCount: rows.length });
  if (changedDuringGen) markBriefStale(personId);
  return content;
}

// A cheap fingerprint of a person's facts, so a regeneration can tell whether the
// facts moved under it while the AI was thinking.
function factSignature(rows: { id: string; status: string; content: string }[]): string {
  return rows.map((r) => `${r.id}:${r.status}:${r.content}`).join("|");
}

// Parse a stored brief row body back into BriefContent, tolerating a legacy or
// corrupt row rather than throwing into a render path.
export function parseBrief(body: string): BriefContent | null {
  try {
    const p = JSON.parse(body);
    if (p && typeof p.read === "string" && Array.isArray(p.insights) && Array.isArray(p.recommendations)) {
      return p as BriefContent;
    }
  } catch {
    /* fall through */
  }
  return null;
}
